from app.models.base import Base
from app.models.permission import Permission, role_permissions
from app.models.role import Role, user_roles
from app.models.user import User
from app.models.module import ModuleRegistry, PillarRegistry
from app.models.notification import Notification
from app.models.applicant_profile import ApplicantProfile
from app.models.audit import AuditLog
from app.models.settings import SystemSetting

# Atharva Veda (NIVARAN) Domain Models
from app.modules.atharva_veda.nivaran.models import (
    NivaranRole,
    CategoryRoutingType,
    GrievanceStatus,
    GrievancePriority,
    HistoryActorType,
    EscalationRole,
    DocumentRequestStatus,
    CommitteeRequestStatus,
    CommitteeStatus,
    CommitteeMemberRole,
    MemberRecommendationType,
    FinalCommitteeDecision,
    FinalRecommendationStatus,
    CommitteeMessageType,
    CommitteeVotingPolicy,
    CommitteePollStatus,
    CommitteeDecisionStatus,
    MeetingType,
    MeetingStatus,
    MeetingOutcome,
    DeanReopenReviewStatus,
    DeanReopenDecisionType,
    SigningKeyStatus,
    DigitalSignatureEntityType,
    EFileStatus,
    ApprovalRequestStatus,
    ApprovalActionType,
    AIProcessingStatus,
    StudentRecordStatus,
    NivaranAuthority,
    SubjectCluster,
    Subject,
    GrievanceCluster,
    Category,
    StudentMasterRecord,
    Grievance,
    GrievanceStatusHistory,
    Comment,
    GrievanceFeedback,
    Assignment,
    ForwardingConfirmation,
    Escalation,
    Document,
    DocumentRequest,
    CommitteeCreationRequest,
    GrievanceCommittee,
    CommitteeMember,
    CommitteeMemberRecommendation,
    CommitteeFinalRecommendation,
    CommitteeMessage,
    CommitteePoll,
    CommitteePollOption,
    CommitteePollVoter,
    CommitteePollVote,
    CommitteeDecisionRecord,
    CommitteeMeeting,
    CommitteeMeetingParticipant,
    DeanReopenReview,
    SigningKeyVersion,
    SigningAuthorizationChallenge,
    DigitalSignature,
    EFile,
    EFileDocument,
    ApprovalRequest,
    ApprovalAction,
    AIProcessingRecord,
    Cluster,
)

__all__ = [
    "Base",
    "User",
    "Role",
    "Permission",
    "user_roles",
    "role_permissions",
    "ApplicantProfile",
    "Notification",
    "ModuleRegistry",
    "PillarRegistry",
    "AuditLog",
    "SystemSetting",
    # Atharva Veda (NIVARAN)
    "NivaranAuthority",
    "SubjectCluster",
    "Subject",
    "GrievanceCluster",
    "Category",
    "StudentMasterRecord",
    "Grievance",
    "GrievanceStatusHistory",
    "Comment",
    "GrievanceFeedback",
    "Assignment",
    "ForwardingConfirmation",
    "Escalation",
    "Document",
    "DocumentRequest",
    "CommitteeCreationRequest",
    "GrievanceCommittee",
    "CommitteeMember",
    "CommitteeMemberRecommendation",
    "CommitteeFinalRecommendation",
    "CommitteeMessage",
    "CommitteePoll",
    "CommitteePollOption",
    "CommitteePollVoter",
    "CommitteePollVote",
    "CommitteeDecisionRecord",
    "CommitteeMeeting",
    "CommitteeMeetingParticipant",
    "DeanReopenReview",
    "SigningKeyVersion",
    "SigningAuthorizationChallenge",
    "DigitalSignature",
    "EFile",
    "EFileDocument",
    "ApprovalRequest",
    "ApprovalAction",
    "AIProcessingRecord",
    "Cluster",
]
