"""initial_40_table_nivaran_schema

Revision ID: cb0e7ff029ea
Revises: 
Create Date: 2026-09-27 03:17:50.662809+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb0e7ff029ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_cluster_number'), 'clusters', ['cluster_number'], unique=True)
    op.create_table('grievance_notification_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('recipient_vyasa_user_id', sa.UUID(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'FAILED', name='outbox_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_notification_outbox_recipient_vyasa_user_id'), 'grievance_notification_outbox', ['recipient_vyasa_user_id'], unique=False)
    op.create_index(op.f('ix_grievance_notification_outbox_status'), 'grievance_notification_outbox', ['status'], unique=False)
    op.create_table('nivaran_authorities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vyasa_user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('APPLICANT', 'MANAGER', 'ASSISTANT_DEAN', 'ASSOCIATE_DEAN', 'DEAN', 'GUEST_MEMBER', name='nivaran_role'), nullable=False),
    sa.Column('name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('email_snapshot', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nivaran_authorities_role'), 'nivaran_authorities', ['role'], unique=False)
    op.create_index(op.f('ix_nivaran_authorities_vyasa_user_id'), 'nivaran_authorities', ['vyasa_user_id'], unique=True)
    op.create_table('signing_key_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('private_key_reference', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RETIRED', 'REVOKED', name='signing_key_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signing_key_versions_fingerprint'), 'signing_key_versions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_signing_key_versions_key_id'), 'signing_key_versions', ['key_id'], unique=True)
    op.create_index(op.f('ix_signing_key_versions_status'), 'signing_key_versions', ['status'], unique=False)
    op.create_table('student_master_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_vyasa_user_id', sa.UUID(), nullable=False),
    sa.Column('record_number', sa.String(length=64), nullable=False),
    sa.Column('registration_number_snapshot', sa.String(length=100), nullable=True),
    sa.Column('enrollment_number_snapshot', sa.String(length=100), nullable=True),
    sa.Column('department_snapshot', sa.String(length=150), nullable=True),
    sa.Column('program_name_snapshot', sa.String(length=150), nullable=True),
    sa.Column('full_name_snapshot', sa.String(length=150), nullable=True),
    sa.Column('email_snapshot', sa.String(length=255), nullable=True),
    sa.Column('mobile_snapshot', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='student_record_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_master_records_enrollment_number_snapshot'), 'student_master_records', ['enrollment_number_snapshot'], unique=False)
    op.create_index(op.f('ix_student_master_records_record_number'), 'student_master_records', ['record_number'], unique=True)
    op.create_index(op.f('ix_student_master_records_registration_number_snapshot'), 'student_master_records', ['registration_number_snapshot'], unique=False)
    op.create_index(op.f('ix_student_master_records_student_vyasa_user_id'), 'student_master_records', ['student_vyasa_user_id'], unique=True)
    op.create_table('grievance_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('associate_dean_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cluster_number BETWEEN 1 AND 3', name='ck_grievance_cluster_number'),
    sa.ForeignKeyConstraint(['associate_dean_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_clusters_associate_dean_id'), 'grievance_clusters', ['associate_dean_id'], unique=True)
    op.create_index(op.f('ix_grievance_clusters_cluster_number'), 'grievance_clusters', ['cluster_number'], unique=True)
    op.create_table('subject_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('assistant_dean_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cluster_number BETWEEN 1 AND 10', name='ck_subject_cluster_number'),
    sa.ForeignKeyConstraint(['assistant_dean_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_clusters_assistant_dean_id'), 'subject_clusters', ['assistant_dean_id'], unique=True)
    op.create_index(op.f('ix_subject_clusters_cluster_number'), 'subject_clusters', ['cluster_number'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('routing_type', sa.Enum('GRIEVANCE_CLUSTER', 'SUBJECT_ASSISTANT_DEAN', 'FIXED_AUTHORITY', name='category_routing_type'), nullable=False),
    sa.Column('grievance_cluster_id', sa.UUID(), nullable=True),
    sa.Column('fixed_authority_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(routing_type = 'GRIEVANCE_CLUSTER' AND grievance_cluster_id IS NOT NULL) OR (routing_type = 'FIXED_AUTHORITY' AND fixed_authority_id IS NOT NULL) OR (routing_type = 'SUBJECT_ASSISTANT_DEAN' AND grievance_cluster_id IS NULL AND fixed_authority_id IS NULL)", name='ck_category_routing'),
    sa.ForeignKeyConstraint(['fixed_authority_id'], ['nivaran_authorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grievance_cluster_id'], ['grievance_clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_fixed_authority_id'), 'categories', ['fixed_authority_id'], unique=False)
    op.create_index(op.f('ix_categories_grievance_cluster_id'), 'categories', ['grievance_cluster_id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('subject_cluster_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_cluster_id'], ['subject_clusters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_index(op.f('ix_subjects_subject_cluster_id'), 'subjects', ['subject_cluster_id'], unique=False)
    op.create_table('grievances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.String(length=30), nullable=False),
    sa.Column('applicant_vyasa_user_id', sa.UUID(), nullable=False),
    sa.Column('student_record_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('final_category_id', sa.UUID(), nullable=True),
    sa.Column('category_reviewed', sa.Boolean(), nullable=False),
    sa.Column('category_overridden', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'AI_PROCESSING', 'PENDING_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_INFORMATION', 'ESCALATED', 'RESOLVED', 'CLOSED', 'REOPENED', name='grievance_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='grievance_priority'), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_authority_id', sa.UUID(), nullable=True),
    sa.Column('closure_remarks', sa.Text(), nullable=True),
    sa.Column('closed_by_authority_id', sa.UUID(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_by_vyasa_user_id', sa.UUID(), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('previous_resolution_notes', sa.Text(), nullable=True),
    sa.Column('previous_resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('previous_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_closure_remarks', sa.Text(), nullable=True),
    sa.Column('previous_closed_by_id', sa.UUID(), nullable=True),
    sa.Column('previous_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closed_by_authority_id'], ['nivaran_authorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['final_category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_closed_by_id'], ['nivaran_authorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_resolved_by_id'], ['nivaran_authorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_authority_id'], ['nivaran_authorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_record_id'], ['student_master_records.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_applicant_vyasa_user_id'), 'grievances', ['applicant_vyasa_user_id'], unique=False)
    op.create_index(op.f('ix_grievances_category_id'), 'grievances', ['category_id'], unique=False)
    op.create_index(op.f('ix_grievances_closed_by_authority_id'), 'grievances', ['closed_by_authority_id'], unique=False)
    op.create_index(op.f('ix_grievances_final_category_id'), 'grievances', ['final_category_id'], unique=False)
    op.create_index(op.f('ix_grievances_grievance_id'), 'grievances', ['grievance_id'], unique=True)
    op.create_index(op.f('ix_grievances_last_action_at'), 'grievances', ['last_action_at'], unique=False)
    op.create_index(op.f('ix_grievances_last_reminder_at'), 'grievances', ['last_reminder_at'], unique=False)
    op.create_index(op.f('ix_grievances_reopened_at'), 'grievances', ['reopened_at'], unique=False)
    op.create_index(op.f('ix_grievances_reopened_by_vyasa_user_id'), 'grievances', ['reopened_by_vyasa_user_id'], unique=False)
    op.create_index(op.f('ix_grievances_resolved_by_authority_id'), 'grievances', ['resolved_by_authority_id'], unique=False)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    op.create_index(op.f('ix_grievances_student_record_id'), 'grievances', ['student_record_id'], unique=False)
    op.create_index(op.f('ix_grievances_subject_id'), 'grievances', ['subject_id'], unique=False)
    op.create_table('ai_processing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('predicted_category_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_processing_status'), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('features_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predicted_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_processing_records_grievance_id'), 'ai_processing_records', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_ai_processing_records_predicted_category_id'), 'ai_processing_records', ['predicted_category_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('requested_from_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('justification_notes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RETURNED_FOR_REVISION', 'CANCELLED', name='approval_request_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_from_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_grievance_id'), 'approval_requests', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_requested_by_id'), 'approval_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_requested_from_id'), 'approval_requests', ['requested_from_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_to'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_assigned_by'), 'assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_assignments_assigned_to'), 'assignments', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_assignments_grievance_id'), 'assignments', ['grievance_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_vyasa_id', sa.UUID(), nullable=True),
    sa.Column('grievance_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_grievance_id'), 'audit_logs', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_vyasa_id'), 'audit_logs', ['user_vyasa_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('user_vyasa_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_grievance_id'), 'comments', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_comments_user_vyasa_id'), 'comments', ['user_vyasa_id'], unique=False)
    op.create_table('committee_creation_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('request_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='committee_request_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggested_chairperson_id', sa.UUID(), nullable=True),
    sa.Column('suggested_members_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['nivaran_authorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_chairperson_id'], ['nivaran_authorities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_creation_requests_grievance_id'), 'committee_creation_requests', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_committee_creation_requests_request_status'), 'committee_creation_requests', ['request_status'], unique=False)
    op.create_index(op.f('ix_committee_creation_requests_requested_by_id'), 'committee_creation_requests', ['requested_by_id'], unique=False)
    op.create_table('dean_reopen_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('dean_id', sa.UUID(), nullable=False),
    sa.Column('concerned_authority_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_REVIEW', 'CLARIFICATION_REQUESTED', 'CLARIFICATION_PROVIDED', 'DECIDED', name='dean_reopen_review_status'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('questioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_type', sa.Enum('UPHOLD_PREVIOUS_RESOLUTION', 'FORWARD_FOR_FRESH_RESOLUTION', 'SEND_FOR_FURTHER_ACTION', 'FURTHER_REVIEW_REQUIRED', name='dean_reopen_decision_type'), nullable=True),
    sa.Column('decision_remarks', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concerned_authority_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dean_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dean_reopen_reviews_concerned_authority_id'), 'dean_reopen_reviews', ['concerned_authority_id'], unique=False)
    op.create_index(op.f('ix_dean_reopen_reviews_dean_id'), 'dean_reopen_reviews', ['dean_id'], unique=False)
    op.create_index(op.f('ix_dean_reopen_reviews_grievance_id'), 'dean_reopen_reviews', ['grievance_id'], unique=True)
    op.create_index(op.f('ix_dean_reopen_reviews_status'), 'dean_reopen_reviews', ['status'], unique=False)
    op.create_table('digital_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signature_version', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('GRIEVANCE_RESOLUTION', 'APPROVAL_DECISION', 'COMMITTEE_FINAL_RECOMMENDATION', name='digital_signature_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('signed_by_id', sa.UUID(), nullable=False),
    sa.Column('signed_by_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('signed_by_role_snapshot', sa.String(length=100), nullable=False),
    sa.Column('signed_by_department_snapshot', sa.String(length=255), nullable=True),
    sa.Column('signed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_algorithm', sa.String(length=50), nullable=False),
    sa.Column('signature_value', sa.Text(), nullable=False),
    sa.Column('key_id', sa.String(length=100), nullable=True),
    sa.Column('key_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('public_key_snapshot', sa.Text(), nullable=True),
    sa.Column('signing_authorization_method', sa.String(length=50), nullable=True),
    sa.Column('signing_authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signed_by_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_signatures_content_hash'), 'digital_signatures', ['content_hash'], unique=False)
    op.create_index(op.f('ix_digital_signatures_entity_id'), 'digital_signatures', ['entity_id'], unique=False)
    op.create_index(op.f('ix_digital_signatures_entity_type'), 'digital_signatures', ['entity_type'], unique=False)
    op.create_index(op.f('ix_digital_signatures_grievance_id'), 'digital_signatures', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_digital_signatures_is_valid'), 'digital_signatures', ['is_valid'], unique=False)
    op.create_index(op.f('ix_digital_signatures_key_fingerprint'), 'digital_signatures', ['key_fingerprint'], unique=False)
    op.create_index(op.f('ix_digital_signatures_key_id'), 'digital_signatures', ['key_id'], unique=False)
    op.create_index(op.f('ix_digital_signatures_signed_at'), 'digital_signatures', ['signed_at'], unique=False)
    op.create_index(op.f('ix_digital_signatures_signed_by_id'), 'digital_signatures', ['signed_by_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_vyasa_user_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_grievance_id'), 'documents', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_vyasa_user_id'), 'documents', ['uploaded_by_vyasa_user_id'], unique=False)
    op.create_table('efiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('e_file_number', sa.String(length=64), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('applicant_vyasa_user_id', sa.UUID(), nullable=False),
    sa.Column('student_record_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', 'ARCHIVED', name='efile_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sealed_by_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_hash', sa.String(length=64), nullable=True),
    sa.Column('pdf_size', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sealed_by_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_record_id'], ['student_master_records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efiles_applicant_vyasa_user_id'), 'efiles', ['applicant_vyasa_user_id'], unique=False)
    op.create_index(op.f('ix_efiles_e_file_number'), 'efiles', ['e_file_number'], unique=True)
    op.create_index(op.f('ix_efiles_grievance_id'), 'efiles', ['grievance_id'], unique=True)
    op.create_index(op.f('ix_efiles_status'), 'efiles', ['status'], unique=False)
    op.create_index(op.f('ix_efiles_student_record_id'), 'efiles', ['student_record_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('from_authority_id', sa.UUID(), nullable=False),
    sa.Column('from_role', sa.Enum('MANAGER', 'ASSISTANT_DEAN', 'ASSOCIATE_DEAN', 'DEAN', name='escalation_role'), nullable=False),
    sa.Column('to_role', sa.Enum('MANAGER', 'ASSISTANT_DEAN', 'ASSOCIATE_DEAN', 'DEAN', name='escalation_role'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_authority_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_from_authority_id'), 'escalations', ['from_authority_id'], unique=False)
    op.create_index(op.f('ix_escalations_grievance_id'), 'escalations', ['grievance_id'], unique=False)
    op.create_table('grievance_committees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('chairperson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'DISSOLVED', name='committee_status'), nullable=False),
    sa.Column('mandate', sa.Text(), nullable=True),
    sa.Column('dissolved_by_id', sa.UUID(), nullable=True),
    sa.Column('dissolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dissolution_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chairperson_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dissolved_by_id'], ['nivaran_authorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_committees_chairperson_id'), 'grievance_committees', ['chairperson_id'], unique=False)
    op.create_index(op.f('ix_grievance_committees_grievance_id'), 'grievance_committees', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_grievance_committees_status'), 'grievance_committees', ['status'], unique=False)
    op.create_table('grievance_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('applicant_vyasa_user_id', sa.UUID(), nullable=False),
    sa.Column('resolution_quality', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.Column('overall_experience', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_experience >= 1 AND overall_experience <= 5', name='ck_feedback_overall_experience'),
    sa.CheckConstraint('resolution_quality >= 1 AND resolution_quality <= 5', name='ck_feedback_resolution_quality'),
    sa.CheckConstraint('response_time >= 1 AND response_time <= 5', name='ck_feedback_response_time'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grievance_id', 'applicant_vyasa_user_id', name='uq_grievance_feedback_grievance_applicant')
    )
    op.create_index(op.f('ix_grievance_feedback_applicant_vyasa_user_id'), 'grievance_feedback', ['applicant_vyasa_user_id'], unique=False)
    op.create_index(op.f('ix_grievance_feedback_grievance_id'), 'grievance_feedback', ['grievance_id'], unique=False)
    op.create_table('grievance_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('SUBMITTED', 'AI_PROCESSING', 'PENDING_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_INFORMATION', 'ESCALATED', 'RESOLVED', 'CLOSED', 'REOPENED', name='grievance_status'), nullable=True),
    sa.Column('new_status', sa.Enum('SUBMITTED', 'AI_PROCESSING', 'PENDING_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_INFORMATION', 'ESCALATED', 'RESOLVED', 'CLOSED', 'REOPENED', name='grievance_status'), nullable=False),
    sa.Column('changed_by_vyasa_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', name='history_actor_type'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_status_history_changed_by_vyasa_user_id'), 'grievance_status_history', ['changed_by_vyasa_user_id'], unique=False)
    op.create_index(op.f('ix_grievance_status_history_grievance_id'), 'grievance_status_history', ['grievance_id'], unique=False)
    op.create_table('signing_authorization_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_vyasa_id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signing_authorization_challenges_grievance_id'), 'signing_authorization_challenges', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_signing_authorization_challenges_payload_hash'), 'signing_authorization_challenges', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_signing_authorization_challenges_purpose'), 'signing_authorization_challenges', ['purpose'], unique=False)
    op.create_index(op.f('ix_signing_authorization_challenges_resource_id'), 'signing_authorization_challenges', ['resource_id'], unique=False)
    op.create_index(op.f('ix_signing_authorization_challenges_user_vyasa_id'), 'signing_authorization_challenges', ['user_vyasa_id'], unique=False)
    op.create_table('approval_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_request_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'RETURNED_FOR_REVISION', 'RESUBMITTED', 'CANCELLED', name='approval_action_type'), nullable=False),
    sa.Column('decision_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('action_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_actions_actor_id'), 'approval_actions', ['actor_id'], unique=False)
    op.create_index(op.f('ix_approval_actions_approval_request_id'), 'approval_actions', ['approval_request_id'], unique=False)
    op.create_table('committee_final_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('chairperson_id', sa.UUID(), nullable=False),
    sa.Column('final_decision', sa.Enum('UPHOLD', 'PARTIALLY_UPHOLD', 'REJECT', 'REQUEST_ADDITIONAL_EVIDENCE', 'RECOMMEND_ADMINISTRATIVE_ACTION', 'RECOMMEND_POLICY_REVIEW', 'OTHER', name='final_committee_decision'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', name='final_recommendation_status'), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('detailed_findings', sa.Text(), nullable=False),
    sa.Column('dissent_summary', sa.Text(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chairperson_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['committee_id'], ['grievance_committees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_final_recommendations_chairperson_id'), 'committee_final_recommendations', ['chairperson_id'], unique=False)
    op.create_index(op.f('ix_committee_final_recommendations_committee_id'), 'committee_final_recommendations', ['committee_id'], unique=True)
    op.create_table('committee_meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('meeting_type', sa.Enum('INTERNAL_COMMITTEE', 'APPLICANT_HEARING', name='meeting_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meet_url', sa.String(length=500), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ONGOING', 'COMPLETED', 'CANCELLED', name='meeting_status'), nullable=False),
    sa.Column('hearing_notes', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('RESOLVED', 'PARTIALLY_RESOLVED', 'FORWARDED', 'REJECTED', 'FURTHER_REVIEW_REQUIRED', name='meeting_outcome'), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['grievance_committees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_meetings_calendar_event_id'), 'committee_meetings', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_committee_meetings_committee_id'), 'committee_meetings', ['committee_id'], unique=False)
    op.create_index(op.f('ix_committee_meetings_created_by_id'), 'committee_meetings', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_committee_meetings_grievance_id'), 'committee_meetings', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_committee_meetings_meeting_type'), 'committee_meetings', ['meeting_type'], unique=False)
    op.create_index(op.f('ix_committee_meetings_scheduled_at'), 'committee_meetings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_committee_meetings_status'), 'committee_meetings', ['status'], unique=False)
    op.create_table('committee_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('member_role', sa.Enum('CHAIRPERSON', 'MEMBER', 'OBSERVER', name='committee_member_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['committee_id'], ['grievance_committees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['removed_by_id'], ['nivaran_authorities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_id', 'authority_id', name='uq_committee_members_committee_authority')
    )
    op.create_index(op.f('ix_committee_members_authority_id'), 'committee_members', ['authority_id'], unique=False)
    op.create_index(op.f('ix_committee_members_committee_id'), 'committee_members', ['committee_id'], unique=False)
    op.create_table('committee_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('MESSAGE', 'SYSTEM', name='committee_message_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['grievance_committees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_messages_committee_id'), 'committee_messages', ['committee_id'], unique=False)
    op.create_index(op.f('ix_committee_messages_sender_id'), 'committee_messages', ['sender_id'], unique=False)
    op.create_table('committee_polls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('voting_policy', sa.Enum('SIMPLE_MAJORITY', 'TWO_THIRDS', 'UNANIMOUS', name='committee_voting_policy'), nullable=False),
    sa.Column('quorum_percentage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='committee_poll_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quorum_percentage BETWEEN 1 AND 100', name='ck_committee_polls_quorum'),
    sa.ForeignKeyConstraint(['committee_id'], ['grievance_committees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_polls_committee_id'), 'committee_polls', ['committee_id'], unique=False)
    op.create_index(op.f('ix_committee_polls_created_by_id'), 'committee_polls', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_committee_polls_status'), 'committee_polls', ['status'], unique=False)
    op.create_table('document_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('request_group_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'APPROVED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='document_request_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['fulfilled_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requests_grievance_id'), 'document_requests', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_document_requests_request_group_id'), 'document_requests', ['request_group_id'], unique=False)
    op.create_index(op.f('ix_document_requests_requested_by_id'), 'document_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_document_requests_status'), 'document_requests', ['status'], unique=False)
    op.create_table('efile_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efile_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('included_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['efile_id'], ['efiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('efile_id', 'document_id', 'document_version', name='uq_efile_document_version')
    )
    op.create_index(op.f('ix_efile_documents_document_id'), 'efile_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_efile_documents_efile_id'), 'efile_documents', ['efile_id'], unique=False)
    op.create_table('forwarding_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('grievance_id', sa.UUID(), nullable=False),
    sa.Column('confirmed_by_id', sa.UUID(), nullable=False),
    sa.Column('target_authority_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_details', sa.Boolean(), nullable=False),
    sa.Column('reviewed_documents', sa.Boolean(), nullable=False),
    sa.Column('understands_status', sa.Boolean(), nullable=False),
    sa.Column('action_taken_within_authority', sa.Boolean(), nullable=False),
    sa.Column('forwarding_necessary', sa.Boolean(), nullable=False),
    sa.Column('accepts_accountability', sa.Boolean(), nullable=False),
    sa.Column('forwarding_reason', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('why_higher_intervention_required', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(action_taken) >= 10', name='ck_forwarding_action_taken_length'),
    sa.CheckConstraint('char_length(forwarding_reason) >= 10', name='ck_forwarding_reason_length'),
    sa.CheckConstraint('char_length(why_higher_intervention_required) >= 10', name='ck_forwarding_why_higher_length'),
    sa.CheckConstraint('reviewed_details = TRUE AND reviewed_documents = TRUE AND understands_status = TRUE AND action_taken_within_authority = TRUE AND forwarding_necessary = TRUE AND accepts_accountability = TRUE', name='ck_forwarding_confirmations_all_checked'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_authority_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forwarding_confirmations_assignment_id'), 'forwarding_confirmations', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_forwarding_confirmations_confirmed_by_id'), 'forwarding_confirmations', ['confirmed_by_id'], unique=False)
    op.create_index(op.f('ix_forwarding_confirmations_grievance_id'), 'forwarding_confirmations', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_forwarding_confirmations_target_authority_id'), 'forwarding_confirmations', ['target_authority_id'], unique=False)
    op.create_table('committee_meeting_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('participant_vyasa_user_id', sa.UUID(), nullable=False),
    sa.Column('participant_role', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['committee_meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'participant_vyasa_user_id', name='uq_committee_meeting_participants_meeting_user')
    )
    op.create_index(op.f('ix_committee_meeting_participants_meeting_id'), 'committee_meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_committee_meeting_participants_participant_vyasa_user_id'), 'committee_meeting_participants', ['participant_vyasa_user_id'], unique=False)
    op.create_table('committee_member_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('UPHOLD', 'PARTIALLY_UPHOLD', 'REJECT', 'REQUEST_ADDITIONAL_EVIDENCE', 'ADMINISTRATIVE_ACTION', 'POLICY_REVIEW', 'OTHER', name='member_recommendation_type'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['grievance_committees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['committee_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_id', 'member_id', name='uq_committee_member_recs_committee_member')
    )
    op.create_index(op.f('ix_committee_member_recommendations_committee_id'), 'committee_member_recommendations', ['committee_id'], unique=False)
    op.create_index(op.f('ix_committee_member_recommendations_member_id'), 'committee_member_recommendations', ['member_id'], unique=False)
    op.create_table('committee_poll_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['committee_polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'display_order', name='uq_committee_poll_options_order'),
    sa.UniqueConstraint('poll_id', 'option_text', name='uq_committee_poll_options_text')
    )
    op.create_index(op.f('ix_committee_poll_options_poll_id'), 'committee_poll_options', ['poll_id'], unique=False)
    op.create_table('committee_poll_voters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('committee_member_id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('institutional_role', sa.String(length=50), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('has_voted', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['committee_member_id'], ['committee_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['committee_polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'authority_id', name='uq_committee_poll_voters_poll_authority')
    )
    op.create_index(op.f('ix_committee_poll_voters_authority_id'), 'committee_poll_voters', ['authority_id'], unique=False)
    op.create_index(op.f('ix_committee_poll_voters_committee_member_id'), 'committee_poll_voters', ['committee_member_id'], unique=False)
    op.create_index(op.f('ix_committee_poll_voters_poll_id'), 'committee_poll_voters', ['poll_id'], unique=False)
    op.create_table('committee_decision_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('decision_status', sa.Enum('RATIFIED', 'FAILED_QUORUM', 'FAILED_MAJORITY', 'TIE', 'REJECTED', name='committee_decision_status'), nullable=False),
    sa.Column('total_eligible_voters', sa.Integer(), nullable=False),
    sa.Column('total_votes_cast', sa.Integer(), nullable=False),
    sa.Column('winning_option_id', sa.UUID(), nullable=True),
    sa.Column('certified_by_id', sa.UUID(), nullable=False),
    sa.Column('certified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certified_by_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['poll_id'], ['committee_polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_option_id'], ['committee_poll_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_decision_records_certified_by_id'), 'committee_decision_records', ['certified_by_id'], unique=False)
    op.create_index(op.f('ix_committee_decision_records_poll_id'), 'committee_decision_records', ['poll_id'], unique=True)
    op.create_table('committee_poll_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('voter_id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['nivaran_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['poll_id'], ['committee_polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['committee_poll_options.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voter_id'], ['committee_poll_voters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'authority_id', name='uq_committee_poll_votes_poll_authority'),
    sa.UniqueConstraint('poll_id', 'voter_id', name='uq_committee_poll_votes_poll_voter')
    )
    op.create_index(op.f('ix_committee_poll_votes_authority_id'), 'committee_poll_votes', ['authority_id'], unique=False)
    op.create_index(op.f('ix_committee_poll_votes_poll_id'), 'committee_poll_votes', ['poll_id'], unique=False)
    op.create_index(op.f('ix_committee_poll_votes_selected_option_id'), 'committee_poll_votes', ['selected_option_id'], unique=False)
    op.create_index(op.f('ix_committee_poll_votes_voter_id'), 'committee_poll_votes', ['voter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_committee_poll_votes_voter_id'), table_name='committee_poll_votes')
    op.drop_index(op.f('ix_committee_poll_votes_selected_option_id'), table_name='committee_poll_votes')
    op.drop_index(op.f('ix_committee_poll_votes_poll_id'), table_name='committee_poll_votes')
    op.drop_index(op.f('ix_committee_poll_votes_authority_id'), table_name='committee_poll_votes')
    op.drop_table('committee_poll_votes')
    op.drop_index(op.f('ix_committee_decision_records_poll_id'), table_name='committee_decision_records')
    op.drop_index(op.f('ix_committee_decision_records_certified_by_id'), table_name='committee_decision_records')
    op.drop_table('committee_decision_records')
    op.drop_index(op.f('ix_committee_poll_voters_poll_id'), table_name='committee_poll_voters')
    op.drop_index(op.f('ix_committee_poll_voters_committee_member_id'), table_name='committee_poll_voters')
    op.drop_index(op.f('ix_committee_poll_voters_authority_id'), table_name='committee_poll_voters')
    op.drop_table('committee_poll_voters')
    op.drop_index(op.f('ix_committee_poll_options_poll_id'), table_name='committee_poll_options')
    op.drop_table('committee_poll_options')
    op.drop_index(op.f('ix_committee_member_recommendations_member_id'), table_name='committee_member_recommendations')
    op.drop_index(op.f('ix_committee_member_recommendations_committee_id'), table_name='committee_member_recommendations')
    op.drop_table('committee_member_recommendations')
    op.drop_index(op.f('ix_committee_meeting_participants_participant_vyasa_user_id'), table_name='committee_meeting_participants')
    op.drop_index(op.f('ix_committee_meeting_participants_meeting_id'), table_name='committee_meeting_participants')
    op.drop_table('committee_meeting_participants')
    op.drop_index(op.f('ix_forwarding_confirmations_target_authority_id'), table_name='forwarding_confirmations')
    op.drop_index(op.f('ix_forwarding_confirmations_grievance_id'), table_name='forwarding_confirmations')
    op.drop_index(op.f('ix_forwarding_confirmations_confirmed_by_id'), table_name='forwarding_confirmations')
    op.drop_index(op.f('ix_forwarding_confirmations_assignment_id'), table_name='forwarding_confirmations')
    op.drop_table('forwarding_confirmations')
    op.drop_index(op.f('ix_efile_documents_efile_id'), table_name='efile_documents')
    op.drop_index(op.f('ix_efile_documents_document_id'), table_name='efile_documents')
    op.drop_table('efile_documents')
    op.drop_index(op.f('ix_document_requests_status'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_requested_by_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_request_group_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_grievance_id'), table_name='document_requests')
    op.drop_table('document_requests')
    op.drop_index(op.f('ix_committee_polls_status'), table_name='committee_polls')
    op.drop_index(op.f('ix_committee_polls_created_by_id'), table_name='committee_polls')
    op.drop_index(op.f('ix_committee_polls_committee_id'), table_name='committee_polls')
    op.drop_table('committee_polls')
    op.drop_index(op.f('ix_committee_messages_sender_id'), table_name='committee_messages')
    op.drop_index(op.f('ix_committee_messages_committee_id'), table_name='committee_messages')
    op.drop_table('committee_messages')
    op.drop_index(op.f('ix_committee_members_committee_id'), table_name='committee_members')
    op.drop_index(op.f('ix_committee_members_authority_id'), table_name='committee_members')
    op.drop_table('committee_members')
    op.drop_index(op.f('ix_committee_meetings_status'), table_name='committee_meetings')
    op.drop_index(op.f('ix_committee_meetings_scheduled_at'), table_name='committee_meetings')
    op.drop_index(op.f('ix_committee_meetings_meeting_type'), table_name='committee_meetings')
    op.drop_index(op.f('ix_committee_meetings_grievance_id'), table_name='committee_meetings')
    op.drop_index(op.f('ix_committee_meetings_created_by_id'), table_name='committee_meetings')
    op.drop_index(op.f('ix_committee_meetings_committee_id'), table_name='committee_meetings')
    op.drop_index(op.f('ix_committee_meetings_calendar_event_id'), table_name='committee_meetings')
    op.drop_table('committee_meetings')
    op.drop_index(op.f('ix_committee_final_recommendations_committee_id'), table_name='committee_final_recommendations')
    op.drop_index(op.f('ix_committee_final_recommendations_chairperson_id'), table_name='committee_final_recommendations')
    op.drop_table('committee_final_recommendations')
    op.drop_index(op.f('ix_approval_actions_approval_request_id'), table_name='approval_actions')
    op.drop_index(op.f('ix_approval_actions_actor_id'), table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_index(op.f('ix_signing_authorization_challenges_user_vyasa_id'), table_name='signing_authorization_challenges')
    op.drop_index(op.f('ix_signing_authorization_challenges_resource_id'), table_name='signing_authorization_challenges')
    op.drop_index(op.f('ix_signing_authorization_challenges_purpose'), table_name='signing_authorization_challenges')
    op.drop_index(op.f('ix_signing_authorization_challenges_payload_hash'), table_name='signing_authorization_challenges')
    op.drop_index(op.f('ix_signing_authorization_challenges_grievance_id'), table_name='signing_authorization_challenges')
    op.drop_table('signing_authorization_challenges')
    op.drop_index(op.f('ix_grievance_status_history_grievance_id'), table_name='grievance_status_history')
    op.drop_index(op.f('ix_grievance_status_history_changed_by_vyasa_user_id'), table_name='grievance_status_history')
    op.drop_table('grievance_status_history')
    op.drop_index(op.f('ix_grievance_feedback_grievance_id'), table_name='grievance_feedback')
    op.drop_index(op.f('ix_grievance_feedback_applicant_vyasa_user_id'), table_name='grievance_feedback')
    op.drop_table('grievance_feedback')
    op.drop_index(op.f('ix_grievance_committees_status'), table_name='grievance_committees')
    op.drop_index(op.f('ix_grievance_committees_grievance_id'), table_name='grievance_committees')
    op.drop_index(op.f('ix_grievance_committees_chairperson_id'), table_name='grievance_committees')
    op.drop_table('grievance_committees')
    op.drop_index(op.f('ix_escalations_grievance_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_from_authority_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_efiles_student_record_id'), table_name='efiles')
    op.drop_index(op.f('ix_efiles_status'), table_name='efiles')
    op.drop_index(op.f('ix_efiles_grievance_id'), table_name='efiles')
    op.drop_index(op.f('ix_efiles_e_file_number'), table_name='efiles')
    op.drop_index(op.f('ix_efiles_applicant_vyasa_user_id'), table_name='efiles')
    op.drop_table('efiles')
    op.drop_index(op.f('ix_documents_uploaded_by_vyasa_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_grievance_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_digital_signatures_signed_by_id'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_signed_at'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_key_id'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_key_fingerprint'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_is_valid'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_grievance_id'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_entity_type'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_entity_id'), table_name='digital_signatures')
    op.drop_index(op.f('ix_digital_signatures_content_hash'), table_name='digital_signatures')
    op.drop_table('digital_signatures')
    op.drop_index(op.f('ix_dean_reopen_reviews_status'), table_name='dean_reopen_reviews')
    op.drop_index(op.f('ix_dean_reopen_reviews_grievance_id'), table_name='dean_reopen_reviews')
    op.drop_index(op.f('ix_dean_reopen_reviews_dean_id'), table_name='dean_reopen_reviews')
    op.drop_index(op.f('ix_dean_reopen_reviews_concerned_authority_id'), table_name='dean_reopen_reviews')
    op.drop_table('dean_reopen_reviews')
    op.drop_index(op.f('ix_committee_creation_requests_requested_by_id'), table_name='committee_creation_requests')
    op.drop_index(op.f('ix_committee_creation_requests_request_status'), table_name='committee_creation_requests')
    op.drop_index(op.f('ix_committee_creation_requests_grievance_id'), table_name='committee_creation_requests')
    op.drop_table('committee_creation_requests')
    op.drop_index(op.f('ix_comments_user_vyasa_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_grievance_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_audit_logs_user_vyasa_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_grievance_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assignments_grievance_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_to'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_by'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requested_from_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requested_by_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_grievance_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_ai_processing_records_predicted_category_id'), table_name='ai_processing_records')
    op.drop_index(op.f('ix_ai_processing_records_grievance_id'), table_name='ai_processing_records')
    op.drop_table('ai_processing_records')
    op.drop_index(op.f('ix_grievances_subject_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_student_record_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_resolved_by_authority_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_reopened_by_vyasa_user_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_reopened_at'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_last_reminder_at'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_last_action_at'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_grievance_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_final_category_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_closed_by_authority_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_category_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_applicant_vyasa_user_id'), table_name='grievances')
    op.drop_table('grievances')
    op.drop_index(op.f('ix_subjects_subject_cluster_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_grievance_cluster_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_fixed_authority_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_subject_clusters_cluster_number'), table_name='subject_clusters')
    op.drop_index(op.f('ix_subject_clusters_assistant_dean_id'), table_name='subject_clusters')
    op.drop_table('subject_clusters')
    op.drop_index(op.f('ix_grievance_clusters_cluster_number'), table_name='grievance_clusters')
    op.drop_index(op.f('ix_grievance_clusters_associate_dean_id'), table_name='grievance_clusters')
    op.drop_table('grievance_clusters')
    op.drop_index(op.f('ix_student_master_records_student_vyasa_user_id'), table_name='student_master_records')
    op.drop_index(op.f('ix_student_master_records_registration_number_snapshot'), table_name='student_master_records')
    op.drop_index(op.f('ix_student_master_records_record_number'), table_name='student_master_records')
    op.drop_index(op.f('ix_student_master_records_enrollment_number_snapshot'), table_name='student_master_records')
    op.drop_table('student_master_records')
    op.drop_index(op.f('ix_signing_key_versions_status'), table_name='signing_key_versions')
    op.drop_index(op.f('ix_signing_key_versions_key_id'), table_name='signing_key_versions')
    op.drop_index(op.f('ix_signing_key_versions_fingerprint'), table_name='signing_key_versions')
    op.drop_table('signing_key_versions')
    op.drop_index(op.f('ix_nivaran_authorities_vyasa_user_id'), table_name='nivaran_authorities')
    op.drop_index(op.f('ix_nivaran_authorities_role'), table_name='nivaran_authorities')
    op.drop_table('nivaran_authorities')
    op.drop_index(op.f('ix_grievance_notification_outbox_status'), table_name='grievance_notification_outbox')
    op.drop_index(op.f('ix_grievance_notification_outbox_recipient_vyasa_user_id'), table_name='grievance_notification_outbox')
    op.drop_table('grievance_notification_outbox')
    op.drop_index(op.f('ix_clusters_cluster_number'), table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
