"""add_applicant_profiles_table

Revision ID: 74bfd3bf7936
Revises: e09046751800
Create Date: 2026-09-27 14:26:22.355952+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74bfd3bf7936'
down_revision: Union[str, None] = 'e09046751800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phd_registration_number', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('subject_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_profiles_phd_registration_number'), 'applicant_profiles', ['phd_registration_number'], unique=True)
    op.create_index(op.f('ix_applicant_profiles_subject_id'), 'applicant_profiles', ['subject_id'], unique=False)
    op.create_index(op.f('ix_applicant_profiles_user_id'), 'applicant_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applicant_profiles_user_id'), table_name='applicant_profiles')
    op.drop_index(op.f('ix_applicant_profiles_subject_id'), table_name='applicant_profiles')
    op.drop_index(op.f('ix_applicant_profiles_phd_registration_number'), table_name='applicant_profiles')
    op.drop_table('applicant_profiles')
    # ### end Alembic commands ###
