import enum


class NivaranRole(str, enum.Enum):
    APPLICANT = "APPLICANT"
    MANAGER = "MANAGER"
    ASSISTANT_DEAN = "ASSISTANT_DEAN"
    ASSOCIATE_DEAN = "ASSOCIATE_DEAN"
    DEAN = "DEAN"
    GUEST_MEMBER = "GUEST_MEMBER"


class CategoryRoutingType(str, enum.Enum):
    CLUSTER = "CLUSTER"
    GRIEVANCE_CLUSTER = "GRIEVANCE_CLUSTER"
    SUBJECT_ASSISTANT_DEAN = "SUBJECT_ASSISTANT_DEAN"
    FIXED_AUTHORITY = "FIXED_AUTHORITY"


class GrievanceStatus(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    AI_PROCESSING = "AI_PROCESSING"
    PENDING_REVIEW = "PENDING_REVIEW"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    AWAITING_INFORMATION = "AWAITING_INFORMATION"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"


class GrievancePriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class HistoryActorType(str, enum.Enum):
    USER = "USER"
    SYSTEM = "SYSTEM"


class EscalationRole(str, enum.Enum):
    MANAGER = "MANAGER"
    ASSISTANT_DEAN = "ASSISTANT_DEAN"
    ASSOCIATE_DEAN = "ASSOCIATE_DEAN"
    DEAN = "DEAN"


class DocumentRequestStatus(str, enum.Enum):
    PENDING = "PENDING"
    UPLOADED = "UPLOADED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class CommitteeRequestStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class CommitteeStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    DISSOLVED = "DISSOLVED"


class CommitteeMemberRole(str, enum.Enum):
    CHAIRPERSON = "CHAIRPERSON"
    MEMBER = "MEMBER"
    OBSERVER = "OBSERVER"


class MemberRecommendationType(str, enum.Enum):
    UPHOLD = "UPHOLD"
    PARTIALLY_UPHOLD = "PARTIALLY_UPHOLD"
    REJECT = "REJECT"
    REQUEST_ADDITIONAL_EVIDENCE = "REQUEST_ADDITIONAL_EVIDENCE"
    ADMINISTRATIVE_ACTION = "ADMINISTRATIVE_ACTION"
    POLICY_REVIEW = "POLICY_REVIEW"
    OTHER = "OTHER"


class FinalCommitteeDecision(str, enum.Enum):
    UPHOLD = "UPHOLD"
    PARTIALLY_UPHOLD = "PARTIALLY_UPHOLD"
    REJECT = "REJECT"
    REQUEST_ADDITIONAL_EVIDENCE = "REQUEST_ADDITIONAL_EVIDENCE"
    RECOMMEND_ADMINISTRATIVE_ACTION = "RECOMMEND_ADMINISTRATIVE_ACTION"
    RECOMMEND_POLICY_REVIEW = "RECOMMEND_POLICY_REVIEW"
    OTHER = "OTHER"


class FinalRecommendationStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    FINALIZED = "FINALIZED"


class CommitteeMessageType(str, enum.Enum):
    MESSAGE = "MESSAGE"
    SYSTEM = "SYSTEM"


class CommitteeVotingPolicy(str, enum.Enum):
    SIMPLE_MAJORITY = "SIMPLE_MAJORITY"
    TWO_THIRDS = "TWO_THIRDS"
    UNANIMOUS = "UNANIMOUS"


class CommitteePollStatus(str, enum.Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class CommitteeDecisionStatus(str, enum.Enum):
    RATIFIED = "RATIFIED"
    FAILED_QUORUM = "FAILED_QUORUM"
    FAILED_MAJORITY = "FAILED_MAJORITY"
    TIE = "TIE"
    REJECTED = "REJECTED"


class MeetingType(str, enum.Enum):
    INTERNAL_COMMITTEE = "INTERNAL_COMMITTEE"
    APPLICANT_HEARING = "APPLICANT_HEARING"


class MeetingStatus(str, enum.Enum):
    SCHEDULED = "SCHEDULED"
    ONGOING = "ONGOING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class MeetingOutcome(str, enum.Enum):
    RESOLVED = "RESOLVED"
    PARTIALLY_RESOLVED = "PARTIALLY_RESOLVED"
    FORWARDED = "FORWARDED"
    REJECTED = "REJECTED"
    FURTHER_REVIEW_REQUIRED = "FURTHER_REVIEW_REQUIRED"


class DeanReopenReviewStatus(str, enum.Enum):
    AWAITING_REVIEW = "AWAITING_REVIEW"
    CLARIFICATION_REQUESTED = "CLARIFICATION_REQUESTED"
    CLARIFICATION_PROVIDED = "CLARIFICATION_PROVIDED"
    DECIDED = "DECIDED"


class DeanReopenDecisionType(str, enum.Enum):
    UPHOLD_PREVIOUS_RESOLUTION = "UPHOLD_PREVIOUS_RESOLUTION"
    FORWARD_FOR_FRESH_RESOLUTION = "FORWARD_FOR_FRESH_RESOLUTION"
    SEND_FOR_FURTHER_ACTION = "SEND_FOR_FURTHER_ACTION"
    FURTHER_REVIEW_REQUIRED = "FURTHER_REVIEW_REQUIRED"


class SigningKeyStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
    REVOKED = "REVOKED"


class DigitalSignatureEntityType(str, enum.Enum):
    GRIEVANCE_RESOLUTION = "GRIEVANCE_RESOLUTION"
    APPROVAL_DECISION = "APPROVAL_DECISION"
    COMMITTEE_FINAL_RECOMMENDATION = "COMMITTEE_FINAL_RECOMMENDATION"


class EFileStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    FINALIZED = "FINALIZED"
    ARCHIVED = "ARCHIVED"


class ApprovalRequestStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RETURNED_FOR_REVISION = "RETURNED_FOR_REVISION"
    CANCELLED = "CANCELLED"


class ApprovalActionType(str, enum.Enum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RETURNED_FOR_REVISION = "RETURNED_FOR_REVISION"
    RESUBMITTED = "RESUBMITTED"
    CANCELLED = "CANCELLED"


class AIProcessingStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class StudentRecordStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ARCHIVED = "ARCHIVED"
