export { AdminDashboardPage } from './pages/AdminDashboardPage';
export { AuthoritiesPage } from './pages/atharva/AuthoritiesPage';
export { SubjectClustersPage } from './pages/atharva/SubjectClustersPage';
export { SubjectsPage } from './pages/atharva/SubjectsPage';
export { GrievanceClustersPage } from './pages/atharva/GrievanceClustersPage';
export { GrievanceCategoriesPage } from './pages/atharva/GrievanceCategoriesPage';
export { AuditLogsPage } from './pages/atharva/AuditLogsPage';
export { AdminNav } from './components/AdminNav';
export { AdminModuleToggleCard } from './components/AdminModuleToggleCard';
export { adminRoutes } from './routes';
export { adminService } from './services/adminService';
export { atharvaAdminService } from './services/atharvaAdminService';
export type { ModuleRegistryItem, AdminStats } from './types';
export * from './types/atharva';
